### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by vzapo**
implemented basic code linter using eslint

currently the branch i pushed has jsut the following simple config:
-always use semicolons;
-string are always double quotes ""
-4 spaces on indentation
-linebreaks style UNIX system

there are still some unused vars that can be removed from the code,but otherwise it is all formatted 

readme is updated on how to use it

in reference to defining a coding style from #46 and also includes #45

### CODE REVIEW

**Comment by vzapo** [comment]
not sure exactly what's the issue with the conflict... the command seems to work on my test and all other commands.

**Comment by vzapo** [comment]
Added airbnb coding style config and formatted the code. Also bumped bot version to 1.2 and updated readme.

**Comment by meleu** [comment]
By looking at the changed files it seems to me that the indentation is 2 spaces. Shouldn't it be 4 spaces?

**Comment by vzapo** [comment]
yeah, apparently they intent by default their nodejs code with 2 spaces instead of 4 based?... strange that I had 4 on my local machine.

Even thou that, now it should be fixed. Indentation should be 4 spaces now as I've also added a rule to enforce 4 spaces style in the `.eslintrc.js`  config.

let me know if now it's all good :)

**Comment by meleu** [comment]
I'm gonna make these changes through different commits. I think it'll be easier to solve the conflicts and keep track of the changes.

I hope you don't mind.

And thanks for letting me know about eslint, the credit is still yours.

(BTW: I used the JSON format for .eslintrc)

**Comment by meleu** [comment]
starting in this commit: 83898c036c60a548efdb9b7e62ee0c358daf621d

**Pull request closed without merging**
