### PR TITLE
refactor: migrate api calls to official library

### PR DESCRIPTION
**Pull request by wescopeland**
This PR:
* Migrates all explicit `API_*.php` calls to RAWeb to now instead use the official JavaScript wrapper library.

### CODE REVIEW

**Comment by wescopeland** [comment]
This has been in review for 5 months.

If there are issues found here, it is likely I will need to redo this work. We should identify a clear steward for RABot so things like this aren't sitting idle forever.

**Comment by meleu** [comment]
sorry bro, I'm unable to test/review.

I'm planning to come back to the scene next week (when I'll be finished with my current project), and then we can restart working on my baby RABot.

**Comment by wescopeland** [comment]
Always great to hear from you @meleu, sounds good.

**Review by luchaos — APPROVED** [review]
lgtm after a cursory scan

**Pull request closed without merging**
